plugins:
  - jekyll-relative-links
  - jekyll-org
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.org
  - README.md
  - LICENSE.org
  - COPYING.org
  - CODE_OF_CONDUCT.org
  - CONTRIBUTING.org
  - ISSUE_TEMPLATE.org
  - PULL_REQUEST_TEMPLATE.org


theme: jekyll-theme-tactile