title: Home
logo: cellsonlove.png
description: 
show_downloads: false
github.is_user_page: false
google_analytics: G-CFDPGX1V1E
theme: jekyll-theme-minimal
name: Pedro Segura's Personal Web-Page
markdown: kramdown
#permalink: /news/:year/:month/:day/:title
