plugins:
  - jekyll-relative-links
  - jekyll-org
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

theme: jekyll-theme-minimal

title: title [The title of your site]
description: [A short description of your site's purpose]
logo: ./cellsonlove.png
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]