plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.org
  - README.org
  - LICENSE.org
  - COPYING.org
  - CODE_OF_CONDUCT.org
  - CONTRIBUTING.org
  - ISSUE_TEMPLATE.org
  - PULL_REQUEST_TEMPLATE.org

